name: NuGetPublisher

# Note: See the following page on how to run this manually so you can provide the forcePublish flag
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
# The shorthand is to go to the github repository and then the Actions tab
# Select the workflow on the left (CI in this case)
# At the top of the list of runs of the workflow there should be a "Run worflow" dropdown
# Use that to select the branch and then you can check whether forcePublish should be on or not
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      forcePublish:
        type: boolean
        description: 'Flag if publishing should be forced even if not on the main branch'
        required: false
        default: false

env:
  NUGET_PUBLISH_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  setup-flags:
    runs-on: ubuntu-latest
    outputs:
      shouldPublish: ${{ steps.set_should_publish.outputs.value }}
    steps:
      - name: Set Force Publish Flag
        id: set_force_publish
        uses: peter-murray/value-as-flag-action@0.0.1
        with:
          value: ${{ github.event.inputs.forcePublish }}
          default: false
          
      - name: Determine Should Publish Flag
        id: determine_should_publish
        if: steps.set_force_publish.outputs.value == 'true' || github.ref == 'refs/heads/main'
        run: echo "value=true" >> $GITHUB_OUTPUT

      - name: Set Should Publish Flag
        id: set_should_publish
        uses: peter-murray/value-as-flag-action@0.0.1
        with:
          value: ${{ steps.determine_should_publish.outputs.value }}
          default: false
          
      - name: Show flags
        run: |
          echo "forcePublish = ${{ steps.set_force_publish.outputs.value }}"
          echo "determineShouldPublish = ${{ steps.determine_should_publish.outputs.value }}"
          echo "github.ref = ${{ github.ref }}"
          echo "shouldPublish = ${{ steps.set_should_publish.outputs.value }}"
          
  git-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  

      # https://github.com/marketplace/actions/git-version
      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.4

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [git-version]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ needs.git-version.outputs.version }}
          prerelease: false
          title: ${{ needs.git-version.outputs.version }}

  build-csharp:
    name: C# Build
    runs-on: windows-latest
    needs: [git-version, setup-flags]
    
    # defaults:
      # run:
        # working-directory: Code/CSharp

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup MSBuild for .NET Framework projects
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Setup NuGet for package restoration
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    # Restore NuGet packages
    - name: Restore NuGet packages
      run: nuget restore MessageSerialization.sln

    # Build the .NET Framework project
    - name: Build project
      run: msbuild MessageSerialization.sln /p:Configuration=Release
    
    # - name: Setup .NET
      # uses: actions/setup-dotnet@v2
      # with:
        # dotnet-version: |
          # 6.0.x
          # 8.0.x  
        # source-url: ${{ env.NUGET_PUBLISH_URL }}
      # env:
        # NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: dotnet restore
      # run: dotnet restore

    # - name: dotnet build
      # run: dotnet build --no-restore -c Release

    # - name: dotnet test
      # run: dotnet test --no-build -c Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
      
    # - name: Publish Test Results
      # uses: dorny/test-reporter@v1
      # if: always()
      # with:
        # name: C# Unit Test Results
        # path: '**/*.trx'
        # reporter: dotnet-trx
      
    - name: Publish MessageSerializer
      run: dotnet publish -c Release -o artifacts/apps/Base -p:Version=${{ needs.git-version.outputs.version }} MessageSerializer/MessageSerializer.csproj

    # Some notes on using GITHUB_TOKEN (note that some of them recommended using dotnet nuget sources add or dotnet nuget add source
    # but that ended up seeming to be unnecessary.  It does look like you need to go to Settings->Actions->General and make sure
    # that GITHUB_TOKEN is allowed to read and write in order to publish
    # https://stackoverflow.com/questions/57889719/how-to-push-nuget-package-in-github-actions
    # https://github.com/NuGet/Home/issues/8580#issuecomment-599056152
    # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository
    - name: Publish MessageSerializer to NuGet
      if: success() && needs.setup-flags.outputs.shouldPublish == 'true'
      run: dotnet nuget push --source ${{ env.NUGET_PUBLISH_URL }} --api-key ${{ secrets.GITHUB_TOKEN }} MessageSerializer/bin/Release/MessageSerializer.${{ needs.git-version.outputs.version }}.nupkg
